### PR TITLE
Allow theming the font family

### LINKED ISSUE #6: Allow theming the font as well
Unfortunately the current first default, Monaco, does not look good for ascii boxes, even if the line height is 1.0, because its box-drawing characters are not full height. So there is a gap. 

Maybe the best would be to keep the current list of default fonts, and allow prepending new ones via the theme?

### PR DESCRIPTION
**Pull request by gaborcsardi**
Currently it replaces the default font family, let me know if you want to prefix instead.

Closes #6.

### CODE REVIEW

**Comment by marionebl** [comment]
This is great, thank you :)

**Comment by gaborcsardi** [comment]
Thanks for merging. One question, though. I could run `npm test` just fine, but for building, I had to make this change:

```diff
diff --git a/src/index.tsx b/src/index.tsx
index 0a57388..d81854d 100644
--- a/src/index.tsx
+++ b/src/index.tsx
@@ -19,7 +19,7 @@ const toViewModel = require('./to-view-model');
 const DEFAULT_THEME = require('./default-theme');

 const StyledContainer = styled.g`
-  font-family: ${props => props.fontFamily};
+  font-family: ${(props: any) => props.fontFamily};
 `;

 export interface SvgTermOptions {
```

Do you want me to add this in another PR?

**Comment by marionebl** [comment]
> Do you want me to add this in another PR?

Yes please

**Comment by gaborcsardi** [comment]
#10

**Pull request merged**
